from meal import convert
from meal import letters

print("LETTERS FUNCTION")
print("AM")
print(letters("12:00am"))
print(type(letters("12:00am")))
print(letters("12:00 am"))
print(letters("12:00a.m."))
print(letters("12:00 a.m."))
print("PM")
print(letters("12:00pm"))
print(letters("12:00 pm"))
print(letters("12:00p.m."))
print(letters("12:00 p.m."))
print(letters("6:00pm"))

print("CONVERT FUNCTION")
print(convert("7:00"))
print(convert("7:30"))
print(convert("800"))
print(convert("12:00"))
print(convert("12:30"))
print(convert("1300"))
print(convert("18:00"))
print(convert("18:30"))

print("CONVERT WITH LETTERS")

print("AM")
print(convert(letters("8:00am")))
print(type(convert(letters("8:00am"))))
print(convert(letters("8:00 am")))
print(convert(letters("8:00a.m.")))
print(convert(letters("8:00 a.m.")))
print(convert(letters("12:00am")))
print(convert(letters("12:00 am")))
print(convert(letters("12:00a.m.")))
print(convert(letters("12:00 a.m.")))

print("PM")
print(convert(letters("12:00 pm")))
print(type(convert(letters("12:00 pm"))))
print(convert(letters("12:00 p.m.")))
print(convert(letters("12:00pm")))
print(convert(letters("12:00p.m.")))
print(convert(letters("6:00 pm")))
print(convert(letters("6:00pm")))
print(convert(letters("6:00p.m.")))
print(convert(letters("6:00 p.m.")))